using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("__NAME__")]
[assembly: AssemblyVersionAttribute("0.0.0.25")]
[assembly: AssemblyFileVersionAttribute("0.0.0.25")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.8490fd182c1ec282d16c4a7285ded654a2c58a5c")]
[assembly: AssemblyTitleAttribute("__NAME__")]
[assembly: AssemblyProductAttribute("__NAME__")]
[assembly: AssemblyDescriptionAttribute("__NAME__ is a product of __NAME__ - https://__REPLACE__@appharbor.com/__REPLACE__" +
    ".git.")]
[assembly: AssemblyTrademarkAttribute("__NAME__ - __NAME__")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011 __NAME__, - Original author or authors")]

